[build]
  command = "npm run build"
  publish = "build"

[context.branch-deploy]
  NPM_FLAGS="--prefix=/dev/null"

# [[redirects]]
#   from = "/blog"
#   to = "/writing"

# [[redirects]]
#   from = "/blog/*"
#   to = "/writing/:splat"
